[tool.poetry]
name = "mztabm2mtbls"
version = "0.1.0"
description = "A library and scripts to convert mzTab-M to MetaboLights ISA-tab format"
authors = ["MetaboLights Team"]
license = "Apache 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
click = "^8.1.7"
metabolights-utils = ">=1.3.6"

[tool.poetry.group.dev.dependencies]
black = "^24.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
